// Hợp đồng gRPC nội bộ giữa booking-service (client) và profile-service (server).
// Chỉ dùng trong mạng Docker nội bộ, KHÔNG public qua API Gateway.
//
// Sinh code: chạy scripts/gen-proto.sh ở thư mục gốc repo. Code sinh ra được commit vào
// từng service (internal/infrastructure/grpc/profilepb) vì mỗi service build với Docker
// context riêng.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: profile/v1/profile.proto

package profilepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookingInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth account id của chuyên gia (chính là expert_id trong booking-service).
	ExpertId string `protobuf:"bytes,1,opt,name=expert_id,json=expertId,proto3" json:"expert_id,omitempty"`
	// Id hồ sơ người khám (patient_records.record_id).
	PatientRecordId string `protobuf:"bytes,2,opt,name=patient_record_id,json=patientRecordId,proto3" json:"patient_record_id,omitempty"`
	// Auth account id của người đặt lịch; hồ sơ phải thuộc tài khoản này.
	OwnerId string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Tuỳ chọn: chuyên khoa bệnh nhân chọn ở bước đầu.
	SpecializationId string `protobuf:"bytes,4,opt,name=specialization_id,json=specializationId,proto3" json:"specialization_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBookingInfoRequest) Reset() {
	*x = GetBookingInfoRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingInfoRequest) ProtoMessage() {}

func (x *GetBookingInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBookingInfoRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookingInfoRequest) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

func (x *GetBookingInfoRequest) GetPatientRecordId() string {
	if x != nil {
		return x.PatientRecordId
	}
	return ""
}

func (x *GetBookingInfoRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetBookingInfoRequest) GetSpecializationId() string {
	if x != nil {
		return x.SpecializationId
	}
	return ""
}

type GetBookingInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expert        *ExpertSummary         `protobuf:"bytes,1,opt,name=expert,proto3" json:"expert,omitempty"`
	PatientRecord *PatientRecord         `protobuf:"bytes,2,opt,name=patient_record,json=patientRecord,proto3" json:"patient_record,omitempty"`
	// Chỉ có giá trị khi request truyền specialization_id.
	Specialization *Specialization `protobuf:"bytes,3,opt,name=specialization,proto3" json:"specialization,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBookingInfoResponse) Reset() {
	*x = GetBookingInfoResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingInfoResponse) ProtoMessage() {}

func (x *GetBookingInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBookingInfoResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookingInfoResponse) GetExpert() *ExpertSummary {
	if x != nil {
		return x.Expert
	}
	return nil
}

func (x *GetBookingInfoResponse) GetPatientRecord() *PatientRecord {
	if x != nil {
		return x.PatientRecord
	}
	return nil
}

func (x *GetBookingInfoResponse) GetSpecialization() *Specialization {
	if x != nil {
		return x.Specialization
	}
	return nil
}

type ExpertSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExpertId           string                 `protobuf:"bytes,1,opt,name=expert_id,json=expertId,proto3" json:"expert_id,omitempty"`
	FullName           string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl          string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Email              string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	VerificationStatus string                 `protobuf:"bytes,5,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
	Specializations    []*Specialization      `protobuf:"bytes,6,rep,name=specializations,proto3" json:"specializations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExpertSummary) Reset() {
	*x = ExpertSummary{}
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertSummary) ProtoMessage() {}

func (x *ExpertSummary) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertSummary.ProtoReflect.Descriptor instead.
func (*ExpertSummary) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ExpertSummary) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

func (x *ExpertSummary) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ExpertSummary) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *ExpertSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ExpertSummary) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

func (x *ExpertSummary) GetSpecializations() []*Specialization {
	if x != nil {
		return x.Specializations
	}
	return nil
}

type Specialization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecId        string                 `protobuf:"bytes,1,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specialization) Reset() {
	*x = Specialization{}
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specialization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specialization) ProtoMessage() {}

func (x *Specialization) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specialization.ProtoReflect.Descriptor instead.
func (*Specialization) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *Specialization) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

func (x *Specialization) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Specialization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PatientRecord struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RecordId string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	OwnerId  string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FullName string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// YYYY-MM-DD, rỗng nếu chưa khai báo.
	DateOfBirth string `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	// MALE / FEMALE / OTHER, rỗng nếu chưa khai báo.
	Gender      string `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber string `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email       string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Address     string `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	// SELF / PARENT / CHILD / SPOUSE / SIBLING / RELATIVE / OTHER
	Relationship  string `protobuf:"bytes,9,opt,name=relationship,proto3" json:"relationship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientRecord) Reset() {
	*x = PatientRecord{}
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientRecord) ProtoMessage() {}

func (x *PatientRecord) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientRecord.ProtoReflect.Descriptor instead.
func (*PatientRecord) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *PatientRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *PatientRecord) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PatientRecord) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *PatientRecord) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *PatientRecord) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PatientRecord) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PatientRecord) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PatientRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PatientRecord) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

var File_profile_v1_profile_proto protoreflect.FileDescriptor

const file_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x18profile/v1/profile.proto\x12\x13mindcare.profile.v1\"\xa8\x01\n" +
	"\x15GetBookingInfoRequest\x12\x1b\n" +
	"\texpert_id\x18\x01 \x01(\tR\bexpertId\x12*\n" +
	"\x11patient_record_id\x18\x02 \x01(\tR\x0fpatientRecordId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12+\n" +
	"\x11specialization_id\x18\x04 \x01(\tR\x10specializationId\"\xec\x01\n" +
	"\x16GetBookingInfoResponse\x12:\n" +
	"\x06expert\x18\x01 \x01(\v2\".mindcare.profile.v1.ExpertSummaryR\x06expert\x12I\n" +
	"\x0epatient_record\x18\x02 \x01(\v2\".mindcare.profile.v1.PatientRecordR\rpatientRecord\x12K\n" +
	"\x0especialization\x18\x03 \x01(\v2#.mindcare.profile.v1.SpecializationR\x0especialization\"\xfe\x01\n" +
	"\rExpertSummary\x12\x1b\n" +
	"\texpert_id\x18\x01 \x01(\tR\bexpertId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12/\n" +
	"\x13verification_status\x18\x05 \x01(\tR\x12verificationStatus\x12M\n" +
	"\x0fspecializations\x18\x06 \x03(\v2#.mindcare.profile.v1.SpecializationR\x0fspecializations\"Q\n" +
	"\x0eSpecialization\x12\x17\n" +
	"\aspec_id\x18\x01 \x01(\tR\x06specId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x97\x02\n" +
	"\rPatientRecord\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\"\n" +
	"\frelationship\x18\t \x01(\tR\frelationship2\x80\x01\n" +
	"\x13ProfileQueryService\x12i\n" +
	"\x0eGetBookingInfo\x12*.mindcare.profile.v1.GetBookingInfoRequest\x1a+.mindcare.profile.v1.GetBookingInfoResponseb\x06proto3"

var (
	file_profile_v1_profile_proto_rawDescOnce sync.Once
	file_profile_v1_profile_proto_rawDescData []byte
)

func file_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)))
	})
	return file_profile_v1_profile_proto_rawDescData
}

var file_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_profile_v1_profile_proto_goTypes = []any{
	(*GetBookingInfoRequest)(nil),  // 0: mindcare.profile.v1.GetBookingInfoRequest
	(*GetBookingInfoResponse)(nil), // 1: mindcare.profile.v1.GetBookingInfoResponse
	(*ExpertSummary)(nil),          // 2: mindcare.profile.v1.ExpertSummary
	(*Specialization)(nil),         // 3: mindcare.profile.v1.Specialization
	(*PatientRecord)(nil),          // 4: mindcare.profile.v1.PatientRecord
}
var file_profile_v1_profile_proto_depIdxs = []int32{
	2, // 0: mindcare.profile.v1.GetBookingInfoResponse.expert:type_name -> mindcare.profile.v1.ExpertSummary
	4, // 1: mindcare.profile.v1.GetBookingInfoResponse.patient_record:type_name -> mindcare.profile.v1.PatientRecord
	3, // 2: mindcare.profile.v1.GetBookingInfoResponse.specialization:type_name -> mindcare.profile.v1.Specialization
	3, // 3: mindcare.profile.v1.ExpertSummary.specializations:type_name -> mindcare.profile.v1.Specialization
	0, // 4: mindcare.profile.v1.ProfileQueryService.GetBookingInfo:input_type -> mindcare.profile.v1.GetBookingInfoRequest
	1, // 5: mindcare.profile.v1.ProfileQueryService.GetBookingInfo:output_type -> mindcare.profile.v1.GetBookingInfoResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_proto_init() }
func file_profile_v1_profile_proto_init() {
	if File_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_profile_v1_profile_proto = out.File
	file_profile_v1_profile_proto_goTypes = nil
	file_profile_v1_profile_proto_depIdxs = nil
}
