// Hợp đồng gRPC nội bộ giữa booking-service, payment-service (client) và profile-service (server).
// Chỉ dùng trong mạng Docker nội bộ, KHÔNG public qua API Gateway.
//
// Sinh code: chạy scripts/gen-proto.sh ở thư mục gốc repo. Code sinh ra được commit vào
// từng service (internal/infrastructure/grpc/profilepb) vì mỗi service build với Docker
// context riêng.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: profile/v1/profile.proto

package profilepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileQueryService_GetBookingInfo_FullMethodName       = "/mindcare.profile.v1.ProfileQueryService/GetBookingInfo"
	ProfileQueryService_ListManagedExpertIds_FullMethodName = "/mindcare.profile.v1.ProfileQueryService/ListManagedExpertIds"
)

// ProfileQueryServiceClient is the client API for ProfileQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileQueryServiceClient interface {
	// GetBookingInfo trả về thông tin cần cho trang xác nhận đặt lịch và lúc tạo cuộc hẹn:
	// chuyên gia, hồ sơ người khám (phải thuộc owner_id) và chuyên khoa đã chọn (nếu có).
	//
	// Lỗi:
	//
	//	INVALID_ARGUMENT    - id không phải UUID hợp lệ
	//	NOT_FOUND           - không có chuyên gia, hoặc hồ sơ không tồn tại/không thuộc owner_id
	//	FAILED_PRECONDITION - chuyên gia không phụ trách chuyên khoa specialization_id
	GetBookingInfo(ctx context.Context, in *GetBookingInfoRequest, opts ...grpc.CallOption) (*GetBookingInfoResponse, error)
	// ListManagedExpertIds trả về auth account id của các chuyên gia do admin_id quản lý
	// (Admin đã duyệt VERIFIED chuyên gia đó). payment-service dùng để giới hạn phạm vi
	// giao dịch Admin được xem/xử lý.
	//
	// Lỗi:
	//
	//	INVALID_ARGUMENT - admin_id không phải UUID hợp lệ
	ListManagedExpertIds(ctx context.Context, in *ListManagedExpertIdsRequest, opts ...grpc.CallOption) (*ListManagedExpertIdsResponse, error)
}

type profileQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileQueryServiceClient(cc grpc.ClientConnInterface) ProfileQueryServiceClient {
	return &profileQueryServiceClient{cc}
}

func (c *profileQueryServiceClient) GetBookingInfo(ctx context.Context, in *GetBookingInfoRequest, opts ...grpc.CallOption) (*GetBookingInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookingInfoResponse)
	err := c.cc.Invoke(ctx, ProfileQueryService_GetBookingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileQueryServiceClient) ListManagedExpertIds(ctx context.Context, in *ListManagedExpertIdsRequest, opts ...grpc.CallOption) (*ListManagedExpertIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManagedExpertIdsResponse)
	err := c.cc.Invoke(ctx, ProfileQueryService_ListManagedExpertIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileQueryServiceServer is the server API for ProfileQueryService service.
// All implementations must embed UnimplementedProfileQueryServiceServer
// for forward compatibility.
type ProfileQueryServiceServer interface {
	// GetBookingInfo trả về thông tin cần cho trang xác nhận đặt lịch và lúc tạo cuộc hẹn:
	// chuyên gia, hồ sơ người khám (phải thuộc owner_id) và chuyên khoa đã chọn (nếu có).
	//
	// Lỗi:
	//
	//	INVALID_ARGUMENT    - id không phải UUID hợp lệ
	//	NOT_FOUND           - không có chuyên gia, hoặc hồ sơ không tồn tại/không thuộc owner_id
	//	FAILED_PRECONDITION - chuyên gia không phụ trách chuyên khoa specialization_id
	GetBookingInfo(context.Context, *GetBookingInfoRequest) (*GetBookingInfoResponse, error)
	// ListManagedExpertIds trả về auth account id của các chuyên gia do admin_id quản lý
	// (Admin đã duyệt VERIFIED chuyên gia đó). payment-service dùng để giới hạn phạm vi
	// giao dịch Admin được xem/xử lý.
	//
	// Lỗi:
	//
	//	INVALID_ARGUMENT - admin_id không phải UUID hợp lệ
	ListManagedExpertIds(context.Context, *ListManagedExpertIdsRequest) (*ListManagedExpertIdsResponse, error)
	mustEmbedUnimplementedProfileQueryServiceServer()
}

// UnimplementedProfileQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileQueryServiceServer struct{}

func (UnimplementedProfileQueryServiceServer) GetBookingInfo(context.Context, *GetBookingInfoRequest) (*GetBookingInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookingInfo not implemented")
}
func (UnimplementedProfileQueryServiceServer) ListManagedExpertIds(context.Context, *ListManagedExpertIdsRequest) (*ListManagedExpertIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListManagedExpertIds not implemented")
}
func (UnimplementedProfileQueryServiceServer) mustEmbedUnimplementedProfileQueryServiceServer() {}
func (UnimplementedProfileQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeProfileQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileQueryServiceServer will
// result in compilation errors.
type UnsafeProfileQueryServiceServer interface {
	mustEmbedUnimplementedProfileQueryServiceServer()
}

func RegisterProfileQueryServiceServer(s grpc.ServiceRegistrar, srv ProfileQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedProfileQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileQueryService_ServiceDesc, srv)
}

func _ProfileQueryService_GetBookingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileQueryServiceServer).GetBookingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileQueryService_GetBookingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileQueryServiceServer).GetBookingInfo(ctx, req.(*GetBookingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileQueryService_ListManagedExpertIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagedExpertIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileQueryServiceServer).ListManagedExpertIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileQueryService_ListManagedExpertIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileQueryServiceServer).ListManagedExpertIds(ctx, req.(*ListManagedExpertIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileQueryService_ServiceDesc is the grpc.ServiceDesc for ProfileQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mindcare.profile.v1.ProfileQueryService",
	HandlerType: (*ProfileQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookingInfo",
			Handler:    _ProfileQueryService_GetBookingInfo_Handler,
		},
		{
			MethodName: "ListManagedExpertIds",
			Handler:    _ProfileQueryService_ListManagedExpertIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile/v1/profile.proto",
}
