// Schema event RabbitMQ do payment-service phát lên exchange "payment.events".
// Routing key: payment.succeeded | payment.failed
//
// Body được serialize bằng protojson nên key JSON theo lowerCamelCase, khớp envelope
// trong RABBITMQ_CONVENTION.md: { eventId, eventType, occurredAt, source, data }.
//
// Sinh code: chạy scripts/gen-proto.sh ở thư mục gốc repo.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: payment/v1/payment_events.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_SUCCESS     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 2
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_SUCCESS",
		2: "PAYMENT_STATUS_FAILED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_SUCCESS":     1,
		"PAYMENT_STATUS_FAILED":      2,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_events_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_events_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_events_proto_rawDescGZIP(), []int{0}
}

type PaymentStatusChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ổn định qua các lần retry (= id outbox event) để consumer xử lý idempotent.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// payment.succeeded | payment.failed
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// RFC3339 UTC
	OccurredAt string `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// payment-service
	Source        string                `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Data          *PaymentStatusChanged `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatusChangedEvent) Reset() {
	*x = PaymentStatusChangedEvent{}
	mi := &file_payment_v1_payment_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatusChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatusChangedEvent) ProtoMessage() {}

func (x *PaymentStatusChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatusChangedEvent.ProtoReflect.Descriptor instead.
func (*PaymentStatusChangedEvent) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_events_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentStatusChangedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PaymentStatusChangedEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PaymentStatusChangedEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *PaymentStatusChangedEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PaymentStatusChangedEvent) GetData() *PaymentStatusChanged {
	if x != nil {
		return x.Data
	}
	return nil
}

type PaymentStatusChanged struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderId string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Rỗng khi order không gắn lịch hẹn (VD: nạp ví).
	AppointmentId string        `protobuf:"bytes,2,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	PayerId       string        `protobuf:"bytes,3,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	ExpertId      string        `protobuf:"bytes,4,opt,name=expert_id,json=expertId,proto3" json:"expert_id,omitempty"`
	AmountVnd     int64         `protobuf:"varint,5,opt,name=amount_vnd,json=amountVnd,proto3" json:"amount_vnd,omitempty"`
	Status        PaymentStatus `protobuf:"varint,6,opt,name=status,proto3,enum=mindcare.payment.v1.PaymentStatus" json:"status,omitempty"`
	// VNPAY | MOMO | MOCK
	Gateway             string `protobuf:"bytes,7,opt,name=gateway,proto3" json:"gateway,omitempty"`
	GatewayTxnRef       string `protobuf:"bytes,8,opt,name=gateway_txn_ref,json=gatewayTxnRef,proto3" json:"gateway_txn_ref,omitempty"`
	GatewayResponseCode string `protobuf:"bytes,9,opt,name=gateway_response_code,json=gatewayResponseCode,proto3" json:"gateway_response_code,omitempty"`
	// Unix millis, 0 khi thanh toán thất bại.
	PaidAt        int64 `protobuf:"varint,10,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatusChanged) Reset() {
	*x = PaymentStatusChanged{}
	mi := &file_payment_v1_payment_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatusChanged) ProtoMessage() {}

func (x *PaymentStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatusChanged.ProtoReflect.Descriptor instead.
func (*PaymentStatusChanged) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_events_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentStatusChanged) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentStatusChanged) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *PaymentStatusChanged) GetPayerId() string {
	if x != nil {
		return x.PayerId
	}
	return ""
}

func (x *PaymentStatusChanged) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

func (x *PaymentStatusChanged) GetAmountVnd() int64 {
	if x != nil {
		return x.AmountVnd
	}
	return 0
}

func (x *PaymentStatusChanged) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentStatusChanged) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *PaymentStatusChanged) GetGatewayTxnRef() string {
	if x != nil {
		return x.GatewayTxnRef
	}
	return ""
}

func (x *PaymentStatusChanged) GetGatewayResponseCode() string {
	if x != nil {
		return x.GatewayResponseCode
	}
	return ""
}

func (x *PaymentStatusChanged) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

var File_payment_v1_payment_events_proto protoreflect.FileDescriptor

const file_payment_v1_payment_events_proto_rawDesc = "" +
	"\n" +
	"\x1fpayment/v1/payment_events.proto\x12\x13mindcare.payment.v1\"\xcd\x01\n" +
	"\x19PaymentStatusChangedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12=\n" +
	"\x04data\x18\x05 \x01(\v2).mindcare.payment.v1.PaymentStatusChangedR\x04data\"\xfa\x02\n" +
	"\x14PaymentStatusChanged\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12%\n" +
	"\x0eappointment_id\x18\x02 \x01(\tR\rappointmentId\x12\x19\n" +
	"\bpayer_id\x18\x03 \x01(\tR\apayerId\x12\x1b\n" +
	"\texpert_id\x18\x04 \x01(\tR\bexpertId\x12\x1d\n" +
	"\n" +
	"amount_vnd\x18\x05 \x01(\x03R\tamountVnd\x12:\n" +
	"\x06status\x18\x06 \x01(\x0e2\".mindcare.payment.v1.PaymentStatusR\x06status\x12\x18\n" +
	"\agateway\x18\a \x01(\tR\agateway\x12&\n" +
	"\x0fgateway_txn_ref\x18\b \x01(\tR\rgatewayTxnRef\x122\n" +
	"\x15gateway_response_code\x18\t \x01(\tR\x13gatewayResponseCode\x12\x17\n" +
	"\apaid_at\x18\n" +
	" \x01(\x03R\x06paidAt*f\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_SUCCESS\x10\x01\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x02b\x06proto3"

var (
	file_payment_v1_payment_events_proto_rawDescOnce sync.Once
	file_payment_v1_payment_events_proto_rawDescData []byte
)

func file_payment_v1_payment_events_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_events_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_events_proto_rawDesc), len(file_payment_v1_payment_events_proto_rawDesc)))
	})
	return file_payment_v1_payment_events_proto_rawDescData
}

var file_payment_v1_payment_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_v1_payment_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_payment_v1_payment_events_proto_goTypes = []any{
	(PaymentStatus)(0),                // 0: mindcare.payment.v1.PaymentStatus
	(*PaymentStatusChangedEvent)(nil), // 1: mindcare.payment.v1.PaymentStatusChangedEvent
	(*PaymentStatusChanged)(nil),      // 2: mindcare.payment.v1.PaymentStatusChanged
}
var file_payment_v1_payment_events_proto_depIdxs = []int32{
	2, // 0: mindcare.payment.v1.PaymentStatusChangedEvent.data:type_name -> mindcare.payment.v1.PaymentStatusChanged
	0, // 1: mindcare.payment.v1.PaymentStatusChanged.status:type_name -> mindcare.payment.v1.PaymentStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_events_proto_init() }
func file_payment_v1_payment_events_proto_init() {
	if File_payment_v1_payment_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_events_proto_rawDesc), len(file_payment_v1_payment_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_v1_payment_events_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_events_proto_depIdxs,
		EnumInfos:         file_payment_v1_payment_events_proto_enumTypes,
		MessageInfos:      file_payment_v1_payment_events_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_events_proto = out.File
	file_payment_v1_payment_events_proto_goTypes = nil
	file_payment_v1_payment_events_proto_depIdxs = nil
}
