// Hợp đồng gRPC nội bộ giữa payment-service (client) và booking-service (server).
// Chỉ dùng trong mạng Docker nội bộ, KHÔNG public qua API Gateway.
// Mọi lời gọi phải gắn metadata "authorization: Bearer <internal JWT>" do auth-service ký,
// booking-service chỉ chấp nhận client_id = payment-service.
//
// Sinh code: chạy scripts/gen-proto.sh ở thư mục gốc repo.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: booking/v1/booking_payment.proto

package bookingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookingPaymentService_ApplyPaymentResult_FullMethodName   = "/mindcare.booking.v1.BookingPaymentService/ApplyPaymentResult"
	BookingPaymentService_GetAppointmentStatus_FullMethodName = "/mindcare.booking.v1.BookingPaymentService/GetAppointmentStatus"
)

// BookingPaymentServiceClient is the client API for BookingPaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingPaymentServiceClient interface {
	// ApplyPaymentResult cập nhật lịch hẹn theo kết quả thanh toán (idempotent):
	//
	//	SUCCESS: PENDING_PAYMENT -> CONFIRMED, slot LOCKED -> OCCUPIED
	//	FAILED:  PENDING_PAYMENT -> CANCELLED, slot LOCKED -> AVAILABLE
	//
	// Gọi lại với cùng kết quả khi lịch hẹn đã ở trạng thái đích trả về OK.
	//
	// Lỗi:
	//
	//	INVALID_ARGUMENT    - appointment_id không hợp lệ hoặc result UNSPECIFIED
	//	NOT_FOUND           - không có lịch hẹn
	//	FAILED_PRECONDITION - trạng thái lịch hẹn/slot không cho phép chuyển (VD: đã huỷ mà thanh toán thành công)
	//	UNAUTHENTICATED / PERMISSION_DENIED - thiếu hoặc sai internal JWT
	ApplyPaymentResult(ctx context.Context, in *ApplyPaymentResultRequest, opts ...grpc.CallOption) (*ApplyPaymentResultResponse, error)
	// GetAppointmentStatus trả về trạng thái hiện tại của lịch hẹn (dùng cho trang kết quả thanh toán).
	GetAppointmentStatus(ctx context.Context, in *GetAppointmentStatusRequest, opts ...grpc.CallOption) (*GetAppointmentStatusResponse, error)
}

type bookingPaymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingPaymentServiceClient(cc grpc.ClientConnInterface) BookingPaymentServiceClient {
	return &bookingPaymentServiceClient{cc}
}

func (c *bookingPaymentServiceClient) ApplyPaymentResult(ctx context.Context, in *ApplyPaymentResultRequest, opts ...grpc.CallOption) (*ApplyPaymentResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPaymentResultResponse)
	err := c.cc.Invoke(ctx, BookingPaymentService_ApplyPaymentResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingPaymentServiceClient) GetAppointmentStatus(ctx context.Context, in *GetAppointmentStatusRequest, opts ...grpc.CallOption) (*GetAppointmentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppointmentStatusResponse)
	err := c.cc.Invoke(ctx, BookingPaymentService_GetAppointmentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingPaymentServiceServer is the server API for BookingPaymentService service.
// All implementations must embed UnimplementedBookingPaymentServiceServer
// for forward compatibility.
type BookingPaymentServiceServer interface {
	// ApplyPaymentResult cập nhật lịch hẹn theo kết quả thanh toán (idempotent):
	//
	//	SUCCESS: PENDING_PAYMENT -> CONFIRMED, slot LOCKED -> OCCUPIED
	//	FAILED:  PENDING_PAYMENT -> CANCELLED, slot LOCKED -> AVAILABLE
	//
	// Gọi lại với cùng kết quả khi lịch hẹn đã ở trạng thái đích trả về OK.
	//
	// Lỗi:
	//
	//	INVALID_ARGUMENT    - appointment_id không hợp lệ hoặc result UNSPECIFIED
	//	NOT_FOUND           - không có lịch hẹn
	//	FAILED_PRECONDITION - trạng thái lịch hẹn/slot không cho phép chuyển (VD: đã huỷ mà thanh toán thành công)
	//	UNAUTHENTICATED / PERMISSION_DENIED - thiếu hoặc sai internal JWT
	ApplyPaymentResult(context.Context, *ApplyPaymentResultRequest) (*ApplyPaymentResultResponse, error)
	// GetAppointmentStatus trả về trạng thái hiện tại của lịch hẹn (dùng cho trang kết quả thanh toán).
	GetAppointmentStatus(context.Context, *GetAppointmentStatusRequest) (*GetAppointmentStatusResponse, error)
	mustEmbedUnimplementedBookingPaymentServiceServer()
}

// UnimplementedBookingPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingPaymentServiceServer struct{}

func (UnimplementedBookingPaymentServiceServer) ApplyPaymentResult(context.Context, *ApplyPaymentResultRequest) (*ApplyPaymentResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPaymentResult not implemented")
}
func (UnimplementedBookingPaymentServiceServer) GetAppointmentStatus(context.Context, *GetAppointmentStatusRequest) (*GetAppointmentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppointmentStatus not implemented")
}
func (UnimplementedBookingPaymentServiceServer) mustEmbedUnimplementedBookingPaymentServiceServer() {}
func (UnimplementedBookingPaymentServiceServer) testEmbeddedByValue()                               {}

// UnsafeBookingPaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingPaymentServiceServer will
// result in compilation errors.
type UnsafeBookingPaymentServiceServer interface {
	mustEmbedUnimplementedBookingPaymentServiceServer()
}

func RegisterBookingPaymentServiceServer(s grpc.ServiceRegistrar, srv BookingPaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedBookingPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookingPaymentService_ServiceDesc, srv)
}

func _BookingPaymentService_ApplyPaymentResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPaymentResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingPaymentServiceServer).ApplyPaymentResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingPaymentService_ApplyPaymentResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingPaymentServiceServer).ApplyPaymentResult(ctx, req.(*ApplyPaymentResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingPaymentService_GetAppointmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppointmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingPaymentServiceServer).GetAppointmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingPaymentService_GetAppointmentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingPaymentServiceServer).GetAppointmentStatus(ctx, req.(*GetAppointmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingPaymentService_ServiceDesc is the grpc.ServiceDesc for BookingPaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingPaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mindcare.booking.v1.BookingPaymentService",
	HandlerType: (*BookingPaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyPaymentResult",
			Handler:    _BookingPaymentService_ApplyPaymentResult_Handler,
		},
		{
			MethodName: "GetAppointmentStatus",
			Handler:    _BookingPaymentService_GetAppointmentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking/v1/booking_payment.proto",
}
