version: '3.8'

services:

  # ================== BOOKING DB ==================
  postgres_booking:
    image: postgres:15-alpine
    container_name: booking_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: booking_db
    ports:
      - "5433:5432"
    volumes:
      - booking_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ================== AUTH DB ==================
  postgres_auth:
    image: postgres:15-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: auth_db
    ports:
      - "5434:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    restart: unless-stopped

  assessment-db:
    image: postgres:15-alpine
    container_name: assessment-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: assessment_db
    ports:
      - "5435:5432" # Máy thật gọi 5435 sẽ vào 5432 của container
    volumes:
      - assessment_data:/var/lib/postgresql/data
    restart: unless-stopped

  profile-db:
    image: postgres:15-alpine
    container_name: profile-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: profile_db
    ports:
      - "5436:5432" # Máy thật gọi 5436 sẽ vào 5432 của container
    volumes:
      - profile_data:/var/lib/postgresql/data
    restart: unless-stopped

  payment-db:
    image: postgres:15-alpine
    container_name: payment-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: payment_db
    ports:
      - "5437:5432" # Máy thật gọi 5437 sẽ vào 5432 của container
    volumes:
      - payment_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ================== REDIS ==================
  redis:
    image: redis:7-alpine
    container_name: mindcare_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # ================== RABBITMQ ==================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mindcare_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  booking_data:
  auth_data:
  assessment_data:
  profile_data:
  payment_data:
  redis_data:
  rabbitmq_data: