// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/payments/bank-accounts": {
            "get": {
                "description": "Retrieve all linked bank accounts for the current expert. Requires EXPERT role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Withdrawals \u0026 Bank Accounts"
                ],
                "summary": "[EXPERT] Get linked bank accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Role (EXPERT)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Link a new bank account for withdrawals. Requires EXPERT role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Withdrawals \u0026 Bank Accounts"
                ],
                "summary": "[EXPERT] Link a new bank account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Role (EXPERT)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Thông tin tài khoản ngân hàng để liên kết",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_withdrawal_handler.LinkBankAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/payments/orders": {
            "post": {
                "description": "Create a payment order for an appointment. Returns the payment URL (e.g. VNPay checkout). Requires PATIENT role or internal call from Booking Service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Orders"
                ],
                "summary": "[PATIENT/SYSTEM] Create a new payment order",
                "parameters": [
                    {
                        "description": "Thông tin khởi tạo giao dịch thanh toán",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_payment_handler.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/payment-service_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_payment_handler.CreateOrderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/payments/vnpay-ipn": {
            "get": {
                "description": "VNPay calls this API to update the payment status of an order. Role: Public (no token required, verifies checksum).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Orders"
                ],
                "summary": "[PUBLIC/WEBHOOK] Receive VNPay payment webhook (IPN)",
                "parameters": [
                    {
                        "type": "object",
                        "description": "VNPay automated response parameters",
                        "name": "queryParams",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/payments/wallets/history": {
            "get": {
                "description": "Retrieve the list of transactions (balance changes) for the current user's wallet, sorted by latest time. Requires PATIENT or EXPERT role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "[PATIENT/EXPERT] Get transaction history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Role (PATIENT hoặc EXPERT)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/payment-service_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_wallet_handler.TxResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/payments/wallets/me": {
            "get": {
                "description": "Retrieve wallet information (available balance, pending balance, locked balance) for the current user. Requires PATIENT or EXPERT role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "[PATIENT/EXPERT] Get current user's wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Role (PATIENT hoặc EXPERT)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/payments/wallets/top-up": {
            "post": {
                "description": "Directly top up the available balance of the current user's wallet. Requires PATIENT or EXPERT role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "[PATIENT/EXPERT] Top up wallet (Dev/Test only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Thông tin nạp tiền",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_wallet_handler.TopUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/payments/withdrawals": {
            "post": {
                "description": "Request a withdrawal to a linked bank account. Amounts \u003c 5,000,000 VND are auto-approved. Requires EXPERT role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Withdrawals \u0026 Bank Accounts"
                ],
                "summary": "[EXPERT] Request a withdrawal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Role (EXPERT)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Thông tin yêu cầu rút tiền",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_withdrawal_handler.CreateWithdrawalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/payments/withdrawals/{id}/approve": {
            "post": {
                "description": "Admin approves a pending withdrawal request. Funds are transferred via Payout Gateway. Requires ADMIN role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Withdrawals"
                ],
                "summary": "[ADMIN] Approve withdrawal request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin ID (UUID)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin Role (ADMIN)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mã yêu cầu rút tiền (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin ghi chú duyệt",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_withdrawal_handler.AdminProcessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/payments/withdrawals/{id}/reject": {
            "post": {
                "description": "Admin rejects a pending withdrawal request. Locked funds are returned to the expert's wallet. Requires ADMIN role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Withdrawals"
                ],
                "summary": "[ADMIN] Reject withdrawal request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin ID (UUID)",
                        "name": "X-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin Role (ADMIN)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mã yêu cầu rút tiền (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lý do từ chối (bắt buộc)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_withdrawal_handler.AdminProcessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/payment-service_pkg_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_payment_handler.CreateOrderRequest": {
            "type": "object",
            "required": [
                "amount",
                "expert_id",
                "gateway",
                "payer_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "expert_id": {
                    "type": "string"
                },
                "gateway": {
                    "description": "VNPAY | MOMO | MOCK",
                    "type": "string"
                },
                "payer_id": {
                    "type": "string"
                }
            }
        },
        "internal_payment_handler.CreateOrderResponse": {
            "type": "object",
            "properties": {
                "commission_amount": {
                    "type": "integer"
                },
                "gross_amount": {
                    "type": "integer"
                },
                "net_amount": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string"
                },
                "payment_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_wallet_handler.TopUpRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                }
            }
        },
        "internal_wallet_handler.TxResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "balance_after": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "reference_id": {
                    "type": "string"
                },
                "reference_type": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "internal_withdrawal_handler.AdminProcessRequest": {
            "type": "object",
            "properties": {
                "note": {
                    "type": "string"
                }
            }
        },
        "internal_withdrawal_handler.CreateWithdrawalRequest": {
            "type": "object",
            "required": [
                "amount",
                "bank_account_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "bank_account_id": {
                    "type": "string"
                }
            }
        },
        "internal_withdrawal_handler.LinkBankAccountRequest": {
            "type": "object",
            "required": [
                "account_holder_name",
                "account_number",
                "bank_code"
            ],
            "properties": {
                "account_holder_name": {
                    "type": "string"
                },
                "account_number": {
                    "type": "string"
                },
                "bank_code": {
                    "type": "string"
                }
            }
        },
        "payment-service_pkg_response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Payment Service API",
	Description:      "Hệ thống thanh toán và ví điện tử - MindCare",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
