// Hợp đồng gRPC nội bộ giữa payment-service (client) và booking-service (server).
// Chỉ dùng trong mạng Docker nội bộ, KHÔNG public qua API Gateway.
// Mọi lời gọi phải gắn metadata "authorization: Bearer <internal JWT>" do auth-service ký,
// booking-service chỉ chấp nhận client_id = payment-service.
//
// Sinh code: chạy scripts/gen-proto.sh ở thư mục gốc repo.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: booking/v1/booking_payment.proto

package bookingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentResult int32

const (
	PaymentResult_PAYMENT_RESULT_UNSPECIFIED PaymentResult = 0
	PaymentResult_PAYMENT_RESULT_SUCCESS     PaymentResult = 1
	PaymentResult_PAYMENT_RESULT_FAILED      PaymentResult = 2
)

// Enum value maps for PaymentResult.
var (
	PaymentResult_name = map[int32]string{
		0: "PAYMENT_RESULT_UNSPECIFIED",
		1: "PAYMENT_RESULT_SUCCESS",
		2: "PAYMENT_RESULT_FAILED",
	}
	PaymentResult_value = map[string]int32{
		"PAYMENT_RESULT_UNSPECIFIED": 0,
		"PAYMENT_RESULT_SUCCESS":     1,
		"PAYMENT_RESULT_FAILED":      2,
	}
)

func (x PaymentResult) Enum() *PaymentResult {
	p := new(PaymentResult)
	*p = x
	return p
}

func (x PaymentResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentResult) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentResult) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_payment_proto_enumTypes[0]
}

func (x PaymentResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentResult.Descriptor instead.
func (PaymentResult) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{0}
}

type AppointmentStatus int32

const (
	AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED     AppointmentStatus = 0
	AppointmentStatus_APPOINTMENT_STATUS_PENDING_PAYMENT AppointmentStatus = 1
	AppointmentStatus_APPOINTMENT_STATUS_CONFIRMED       AppointmentStatus = 2
	AppointmentStatus_APPOINTMENT_STATUS_CANCELLED       AppointmentStatus = 3
	AppointmentStatus_APPOINTMENT_STATUS_COMPLETED       AppointmentStatus = 4
)

// Enum value maps for AppointmentStatus.
var (
	AppointmentStatus_name = map[int32]string{
		0: "APPOINTMENT_STATUS_UNSPECIFIED",
		1: "APPOINTMENT_STATUS_PENDING_PAYMENT",
		2: "APPOINTMENT_STATUS_CONFIRMED",
		3: "APPOINTMENT_STATUS_CANCELLED",
		4: "APPOINTMENT_STATUS_COMPLETED",
	}
	AppointmentStatus_value = map[string]int32{
		"APPOINTMENT_STATUS_UNSPECIFIED":     0,
		"APPOINTMENT_STATUS_PENDING_PAYMENT": 1,
		"APPOINTMENT_STATUS_CONFIRMED":       2,
		"APPOINTMENT_STATUS_CANCELLED":       3,
		"APPOINTMENT_STATUS_COMPLETED":       4,
	}
)

func (x AppointmentStatus) Enum() *AppointmentStatus {
	p := new(AppointmentStatus)
	*p = x
	return p
}

func (x AppointmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppointmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_payment_proto_enumTypes[1].Descriptor()
}

func (AppointmentStatus) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_payment_proto_enumTypes[1]
}

func (x AppointmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppointmentStatus.Descriptor instead.
func (AppointmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{1}
}

type ApplyPaymentResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	// Id payment order (payment_orders.id), dùng để log/truy vết.
	OrderId       string        `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Result        PaymentResult `protobuf:"varint,3,opt,name=result,proto3,enum=mindcare.booking.v1.PaymentResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentResultRequest) Reset() {
	*x = ApplyPaymentResultRequest{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentResultRequest) ProtoMessage() {}

func (x *ApplyPaymentResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentResultRequest.ProtoReflect.Descriptor instead.
func (*ApplyPaymentResultRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyPaymentResultRequest) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *ApplyPaymentResultRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ApplyPaymentResultRequest) GetResult() PaymentResult {
	if x != nil {
		return x.Result
	}
	return PaymentResult_PAYMENT_RESULT_UNSPECIFIED
}

type ApplyPaymentResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=mindcare.booking.v1.AppointmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentResultResponse) Reset() {
	*x = ApplyPaymentResultResponse{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentResultResponse) ProtoMessage() {}

func (x *ApplyPaymentResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentResultResponse.ProtoReflect.Descriptor instead.
func (*ApplyPaymentResultResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyPaymentResultResponse) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *ApplyPaymentResultResponse) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

type GetAppointmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentStatusRequest) Reset() {
	*x = GetAppointmentStatusRequest{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentStatusRequest) ProtoMessage() {}

func (x *GetAppointmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppointmentStatusRequest) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

type GetAppointmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=mindcare.booking.v1.AppointmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentStatusResponse) Reset() {
	*x = GetAppointmentStatusResponse{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentStatusResponse) ProtoMessage() {}

func (x *GetAppointmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppointmentStatusResponse) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *GetAppointmentStatusResponse) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

type GetAppointmentSummariesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppointmentIds []string               `protobuf:"bytes,1,rep,name=appointment_ids,json=appointmentIds,proto3" json:"appointment_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAppointmentSummariesRequest) Reset() {
	*x = GetAppointmentSummariesRequest{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentSummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentSummariesRequest) ProtoMessage() {}

func (x *GetAppointmentSummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentSummariesRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentSummariesRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppointmentSummariesRequest) GetAppointmentIds() []string {
	if x != nil {
		return x.AppointmentIds
	}
	return nil
}

type GetAppointmentSummariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*AppointmentSummary  `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentSummariesResponse) Reset() {
	*x = GetAppointmentSummariesResponse{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentSummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentSummariesResponse) ProtoMessage() {}

func (x *GetAppointmentSummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentSummariesResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentSummariesResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppointmentSummariesResponse) GetAppointments() []*AppointmentSummary {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type AppointmentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	// Auth account id của bệnh nhân đặt lịch và chuyên gia.
	PatientId string            `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ExpertId  string            `protobuf:"bytes,3,opt,name=expert_id,json=expertId,proto3" json:"expert_id,omitempty"`
	Status    AppointmentStatus `protobuf:"varint,4,opt,name=status,proto3,enum=mindcare.booking.v1.AppointmentStatus" json:"status,omitempty"`
	// Giờ khám (Unix ms) và giá slot (VND).
	StartTime          int64  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            int64  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PriceVnd           int64  `protobuf:"varint,7,opt,name=price_vnd,json=priceVnd,proto3" json:"price_vnd,omitempty"`
	SpecializationName string `protobuf:"bytes,8,opt,name=specialization_name,json=specializationName,proto3" json:"specialization_name,omitempty"`
	// Tên người khám (hồ sơ người khám lúc đặt lịch, có thể khác chủ tài khoản).
	PatientFullName string `protobuf:"bytes,9,opt,name=patient_full_name,json=patientFullName,proto3" json:"patient_full_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppointmentSummary) Reset() {
	*x = AppointmentSummary{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentSummary) ProtoMessage() {}

func (x *AppointmentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentSummary.ProtoReflect.Descriptor instead.
func (*AppointmentSummary) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{6}
}

func (x *AppointmentSummary) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *AppointmentSummary) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AppointmentSummary) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

func (x *AppointmentSummary) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

func (x *AppointmentSummary) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AppointmentSummary) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *AppointmentSummary) GetPriceVnd() int64 {
	if x != nil {
		return x.PriceVnd
	}
	return 0
}

func (x *AppointmentSummary) GetSpecializationName() string {
	if x != nil {
		return x.SpecializationName
	}
	return ""
}

func (x *AppointmentSummary) GetPatientFullName() string {
	if x != nil {
		return x.PatientFullName
	}
	return ""
}

var File_booking_v1_booking_payment_proto protoreflect.FileDescriptor

const file_booking_v1_booking_payment_proto_rawDesc = "" +
	"\n" +
	" booking/v1/booking_payment.proto\x12\x13mindcare.booking.v1\"\x99\x01\n" +
	"\x19ApplyPaymentResultRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12:\n" +
	"\x06result\x18\x03 \x01(\x0e2\".mindcare.booking.v1.PaymentResultR\x06result\"\x83\x01\n" +
	"\x1aApplyPaymentResultResponse\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.mindcare.booking.v1.AppointmentStatusR\x06status\"D\n" +
	"\x1bGetAppointmentStatusRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\"\x85\x01\n" +
	"\x1cGetAppointmentStatusResponse\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.mindcare.booking.v1.AppointmentStatusR\x06status\"I\n" +
	"\x1eGetAppointmentSummariesRequest\x12'\n" +
	"\x0fappointment_ids\x18\x01 \x03(\tR\x0eappointmentIds\"n\n" +
	"\x1fGetAppointmentSummariesResponse\x12K\n" +
	"\fappointments\x18\x01 \x03(\v2'.mindcare.booking.v1.AppointmentSummaryR\fappointments\"\xeb\x02\n" +
	"\x12AppointmentSummary\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\texpert_id\x18\x03 \x01(\tR\bexpertId\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2&.mindcare.booking.v1.AppointmentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x1b\n" +
	"\tprice_vnd\x18\a \x01(\x03R\bpriceVnd\x12/\n" +
	"\x13specialization_name\x18\b \x01(\tR\x12specializationName\x12*\n" +
	"\x11patient_full_name\x18\t \x01(\tR\x0fpatientFullName*f\n" +
	"\rPaymentResult\x12\x1e\n" +
	"\x1aPAYMENT_RESULT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_RESULT_SUCCESS\x10\x01\x12\x19\n" +
	"\x15PAYMENT_RESULT_FAILED\x10\x02*\xc5\x01\n" +
	"\x11AppointmentStatus\x12\"\n" +
	"\x1eAPPOINTMENT_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"APPOINTMENT_STATUS_PENDING_PAYMENT\x10\x01\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_CONFIRMED\x10\x02\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_CANCELLED\x10\x03\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_COMPLETED\x10\x042\x92\x03\n" +
	"\x15BookingPaymentService\x12u\n" +
	"\x12ApplyPaymentResult\x12..mindcare.booking.v1.ApplyPaymentResultRequest\x1a/.mindcare.booking.v1.ApplyPaymentResultResponse\x12{\n" +
	"\x14GetAppointmentStatus\x120.mindcare.booking.v1.GetAppointmentStatusRequest\x1a1.mindcare.booking.v1.GetAppointmentStatusResponse\x12\x84\x01\n" +
	"\x17GetAppointmentSummaries\x123.mindcare.booking.v1.GetAppointmentSummariesRequest\x1a4.mindcare.booking.v1.GetAppointmentSummariesResponseb\x06proto3"

var (
	file_booking_v1_booking_payment_proto_rawDescOnce sync.Once
	file_booking_v1_booking_payment_proto_rawDescData []byte
)

func file_booking_v1_booking_payment_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_payment_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_payment_proto_rawDesc), len(file_booking_v1_booking_payment_proto_rawDesc)))
	})
	return file_booking_v1_booking_payment_proto_rawDescData
}

var file_booking_v1_booking_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_booking_v1_booking_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_booking_v1_booking_payment_proto_goTypes = []any{
	(PaymentResult)(0),                      // 0: mindcare.booking.v1.PaymentResult
	(AppointmentStatus)(0),                  // 1: mindcare.booking.v1.AppointmentStatus
	(*ApplyPaymentResultRequest)(nil),       // 2: mindcare.booking.v1.ApplyPaymentResultRequest
	(*ApplyPaymentResultResponse)(nil),      // 3: mindcare.booking.v1.ApplyPaymentResultResponse
	(*GetAppointmentStatusRequest)(nil),     // 4: mindcare.booking.v1.GetAppointmentStatusRequest
	(*GetAppointmentStatusResponse)(nil),    // 5: mindcare.booking.v1.GetAppointmentStatusResponse
	(*GetAppointmentSummariesRequest)(nil),  // 6: mindcare.booking.v1.GetAppointmentSummariesRequest
	(*GetAppointmentSummariesResponse)(nil), // 7: mindcare.booking.v1.GetAppointmentSummariesResponse
	(*AppointmentSummary)(nil),              // 8: mindcare.booking.v1.AppointmentSummary
}
var file_booking_v1_booking_payment_proto_depIdxs = []int32{
	0, // 0: mindcare.booking.v1.ApplyPaymentResultRequest.result:type_name -> mindcare.booking.v1.PaymentResult
	1, // 1: mindcare.booking.v1.ApplyPaymentResultResponse.status:type_name -> mindcare.booking.v1.AppointmentStatus
	1, // 2: mindcare.booking.v1.GetAppointmentStatusResponse.status:type_name -> mindcare.booking.v1.AppointmentStatus
	8, // 3: mindcare.booking.v1.GetAppointmentSummariesResponse.appointments:type_name -> mindcare.booking.v1.AppointmentSummary
	1, // 4: mindcare.booking.v1.AppointmentSummary.status:type_name -> mindcare.booking.v1.AppointmentStatus
	2, // 5: mindcare.booking.v1.BookingPaymentService.ApplyPaymentResult:input_type -> mindcare.booking.v1.ApplyPaymentResultRequest
	4, // 6: mindcare.booking.v1.BookingPaymentService.GetAppointmentStatus:input_type -> mindcare.booking.v1.GetAppointmentStatusRequest
	6, // 7: mindcare.booking.v1.BookingPaymentService.GetAppointmentSummaries:input_type -> mindcare.booking.v1.GetAppointmentSummariesRequest
	3, // 8: mindcare.booking.v1.BookingPaymentService.ApplyPaymentResult:output_type -> mindcare.booking.v1.ApplyPaymentResultResponse
	5, // 9: mindcare.booking.v1.BookingPaymentService.GetAppointmentStatus:output_type -> mindcare.booking.v1.GetAppointmentStatusResponse
	7, // 10: mindcare.booking.v1.BookingPaymentService.GetAppointmentSummaries:output_type -> mindcare.booking.v1.GetAppointmentSummariesResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_payment_proto_init() }
func file_booking_v1_booking_payment_proto_init() {
	if File_booking_v1_booking_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_payment_proto_rawDesc), len(file_booking_v1_booking_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_payment_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_payment_proto_depIdxs,
		EnumInfos:         file_booking_v1_booking_payment_proto_enumTypes,
		MessageInfos:      file_booking_v1_booking_payment_proto_msgTypes,
	}.Build()
	File_booking_v1_booking_payment_proto = out.File
	file_booking_v1_booking_payment_proto_goTypes = nil
	file_booking_v1_booking_payment_proto_depIdxs = nil
}
