// Hợp đồng gRPC nội bộ giữa payment-service (client) và booking-service (server).
// Chỉ dùng trong mạng Docker nội bộ, KHÔNG public qua API Gateway.
// Mọi lời gọi phải gắn metadata "authorization: Bearer <internal JWT>" do auth-service ký,
// booking-service chỉ chấp nhận client_id = payment-service.
//
// Sinh code: chạy scripts/gen-proto.sh ở thư mục gốc repo.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: booking/v1/booking_payment.proto

package bookingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentResult int32

const (
	PaymentResult_PAYMENT_RESULT_UNSPECIFIED PaymentResult = 0
	PaymentResult_PAYMENT_RESULT_SUCCESS     PaymentResult = 1
	PaymentResult_PAYMENT_RESULT_FAILED      PaymentResult = 2
)

// Enum value maps for PaymentResult.
var (
	PaymentResult_name = map[int32]string{
		0: "PAYMENT_RESULT_UNSPECIFIED",
		1: "PAYMENT_RESULT_SUCCESS",
		2: "PAYMENT_RESULT_FAILED",
	}
	PaymentResult_value = map[string]int32{
		"PAYMENT_RESULT_UNSPECIFIED": 0,
		"PAYMENT_RESULT_SUCCESS":     1,
		"PAYMENT_RESULT_FAILED":      2,
	}
)

func (x PaymentResult) Enum() *PaymentResult {
	p := new(PaymentResult)
	*p = x
	return p
}

func (x PaymentResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentResult) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentResult) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_payment_proto_enumTypes[0]
}

func (x PaymentResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentResult.Descriptor instead.
func (PaymentResult) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{0}
}

type AppointmentStatus int32

const (
	AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED     AppointmentStatus = 0
	AppointmentStatus_APPOINTMENT_STATUS_PENDING_PAYMENT AppointmentStatus = 1
	AppointmentStatus_APPOINTMENT_STATUS_CONFIRMED       AppointmentStatus = 2
	AppointmentStatus_APPOINTMENT_STATUS_CANCELLED       AppointmentStatus = 3
	AppointmentStatus_APPOINTMENT_STATUS_COMPLETED       AppointmentStatus = 4
)

// Enum value maps for AppointmentStatus.
var (
	AppointmentStatus_name = map[int32]string{
		0: "APPOINTMENT_STATUS_UNSPECIFIED",
		1: "APPOINTMENT_STATUS_PENDING_PAYMENT",
		2: "APPOINTMENT_STATUS_CONFIRMED",
		3: "APPOINTMENT_STATUS_CANCELLED",
		4: "APPOINTMENT_STATUS_COMPLETED",
	}
	AppointmentStatus_value = map[string]int32{
		"APPOINTMENT_STATUS_UNSPECIFIED":     0,
		"APPOINTMENT_STATUS_PENDING_PAYMENT": 1,
		"APPOINTMENT_STATUS_CONFIRMED":       2,
		"APPOINTMENT_STATUS_CANCELLED":       3,
		"APPOINTMENT_STATUS_COMPLETED":       4,
	}
)

func (x AppointmentStatus) Enum() *AppointmentStatus {
	p := new(AppointmentStatus)
	*p = x
	return p
}

func (x AppointmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppointmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_payment_proto_enumTypes[1].Descriptor()
}

func (AppointmentStatus) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_payment_proto_enumTypes[1]
}

func (x AppointmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppointmentStatus.Descriptor instead.
func (AppointmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{1}
}

type ApplyPaymentResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	// Id payment order (payment_orders.id), dùng để log/truy vết.
	OrderId       string        `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Result        PaymentResult `protobuf:"varint,3,opt,name=result,proto3,enum=mindcare.booking.v1.PaymentResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentResultRequest) Reset() {
	*x = ApplyPaymentResultRequest{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentResultRequest) ProtoMessage() {}

func (x *ApplyPaymentResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentResultRequest.ProtoReflect.Descriptor instead.
func (*ApplyPaymentResultRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyPaymentResultRequest) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *ApplyPaymentResultRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ApplyPaymentResultRequest) GetResult() PaymentResult {
	if x != nil {
		return x.Result
	}
	return PaymentResult_PAYMENT_RESULT_UNSPECIFIED
}

type ApplyPaymentResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=mindcare.booking.v1.AppointmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentResultResponse) Reset() {
	*x = ApplyPaymentResultResponse{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentResultResponse) ProtoMessage() {}

func (x *ApplyPaymentResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentResultResponse.ProtoReflect.Descriptor instead.
func (*ApplyPaymentResultResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyPaymentResultResponse) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *ApplyPaymentResultResponse) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

type GetAppointmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentStatusRequest) Reset() {
	*x = GetAppointmentStatusRequest{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentStatusRequest) ProtoMessage() {}

func (x *GetAppointmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppointmentStatusRequest) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

type GetAppointmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=mindcare.booking.v1.AppointmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentStatusResponse) Reset() {
	*x = GetAppointmentStatusResponse{}
	mi := &file_booking_v1_booking_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentStatusResponse) ProtoMessage() {}

func (x *GetAppointmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppointmentStatusResponse) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *GetAppointmentStatusResponse) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

var File_booking_v1_booking_payment_proto protoreflect.FileDescriptor

const file_booking_v1_booking_payment_proto_rawDesc = "" +
	"\n" +
	" booking/v1/booking_payment.proto\x12\x13mindcare.booking.v1\"\x99\x01\n" +
	"\x19ApplyPaymentResultRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12:\n" +
	"\x06result\x18\x03 \x01(\x0e2\".mindcare.booking.v1.PaymentResultR\x06result\"\x83\x01\n" +
	"\x1aApplyPaymentResultResponse\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.mindcare.booking.v1.AppointmentStatusR\x06status\"D\n" +
	"\x1bGetAppointmentStatusRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\"\x85\x01\n" +
	"\x1cGetAppointmentStatusResponse\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.mindcare.booking.v1.AppointmentStatusR\x06status*f\n" +
	"\rPaymentResult\x12\x1e\n" +
	"\x1aPAYMENT_RESULT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_RESULT_SUCCESS\x10\x01\x12\x19\n" +
	"\x15PAYMENT_RESULT_FAILED\x10\x02*\xc5\x01\n" +
	"\x11AppointmentStatus\x12\"\n" +
	"\x1eAPPOINTMENT_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"APPOINTMENT_STATUS_PENDING_PAYMENT\x10\x01\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_CONFIRMED\x10\x02\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_CANCELLED\x10\x03\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_COMPLETED\x10\x042\x8b\x02\n" +
	"\x15BookingPaymentService\x12u\n" +
	"\x12ApplyPaymentResult\x12..mindcare.booking.v1.ApplyPaymentResultRequest\x1a/.mindcare.booking.v1.ApplyPaymentResultResponse\x12{\n" +
	"\x14GetAppointmentStatus\x120.mindcare.booking.v1.GetAppointmentStatusRequest\x1a1.mindcare.booking.v1.GetAppointmentStatusResponseb\x06proto3"

var (
	file_booking_v1_booking_payment_proto_rawDescOnce sync.Once
	file_booking_v1_booking_payment_proto_rawDescData []byte
)

func file_booking_v1_booking_payment_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_payment_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_payment_proto_rawDesc), len(file_booking_v1_booking_payment_proto_rawDesc)))
	})
	return file_booking_v1_booking_payment_proto_rawDescData
}

var file_booking_v1_booking_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_booking_v1_booking_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_booking_v1_booking_payment_proto_goTypes = []any{
	(PaymentResult)(0),                   // 0: mindcare.booking.v1.PaymentResult
	(AppointmentStatus)(0),               // 1: mindcare.booking.v1.AppointmentStatus
	(*ApplyPaymentResultRequest)(nil),    // 2: mindcare.booking.v1.ApplyPaymentResultRequest
	(*ApplyPaymentResultResponse)(nil),   // 3: mindcare.booking.v1.ApplyPaymentResultResponse
	(*GetAppointmentStatusRequest)(nil),  // 4: mindcare.booking.v1.GetAppointmentStatusRequest
	(*GetAppointmentStatusResponse)(nil), // 5: mindcare.booking.v1.GetAppointmentStatusResponse
}
var file_booking_v1_booking_payment_proto_depIdxs = []int32{
	0, // 0: mindcare.booking.v1.ApplyPaymentResultRequest.result:type_name -> mindcare.booking.v1.PaymentResult
	1, // 1: mindcare.booking.v1.ApplyPaymentResultResponse.status:type_name -> mindcare.booking.v1.AppointmentStatus
	1, // 2: mindcare.booking.v1.GetAppointmentStatusResponse.status:type_name -> mindcare.booking.v1.AppointmentStatus
	2, // 3: mindcare.booking.v1.BookingPaymentService.ApplyPaymentResult:input_type -> mindcare.booking.v1.ApplyPaymentResultRequest
	4, // 4: mindcare.booking.v1.BookingPaymentService.GetAppointmentStatus:input_type -> mindcare.booking.v1.GetAppointmentStatusRequest
	3, // 5: mindcare.booking.v1.BookingPaymentService.ApplyPaymentResult:output_type -> mindcare.booking.v1.ApplyPaymentResultResponse
	5, // 6: mindcare.booking.v1.BookingPaymentService.GetAppointmentStatus:output_type -> mindcare.booking.v1.GetAppointmentStatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_payment_proto_init() }
func file_booking_v1_booking_payment_proto_init() {
	if File_booking_v1_booking_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_payment_proto_rawDesc), len(file_booking_v1_booking_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_payment_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_payment_proto_depIdxs,
		EnumInfos:         file_booking_v1_booking_payment_proto_enumTypes,
		MessageInfos:      file_booking_v1_booking_payment_proto_msgTypes,
	}.Build()
	File_booking_v1_booking_payment_proto = out.File
	file_booking_v1_booking_payment_proto_goTypes = nil
	file_booking_v1_booking_payment_proto_depIdxs = nil
}
