# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./app/frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./app/frontend
        run: npm ci

      - name: Build FE
        working-directory: ./app/frontend
        run: npm run build

      - name: Run test
        working-directory: ./app/frontend
        run: npm run test:run

  build-go-services:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [profile-service, payment-service, booking-service]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.x"
          cache: true
          cache-dependency-path: app/backend/${{ matrix.service }}/go.sum

      - name: Build
        working-directory: ./app/backend/${{ matrix.service }}
        run: go build -v ./...

      - name: Test
        working-directory: ./app/backend/${{ matrix.service }}
        run: go test -v ./...

  build-auth-service:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:15-alpine
    #     env:
    #       POSTGRES_USER: root
    #       POSTGRES_PASSWORD: rootpassword
    #       POSTGRES_DB: auth_db
    #     ports:
    #       - 5434:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
          cache-dependency-path: app/backend/auth-service/pom.xml

      - name: Make mvnw executable
        working-directory: ./app/backend/auth-service
        run: chmod +x mvnw

      - name: Build with Maven
        working-directory: ./app/backend/auth-service
        run: ./mvnw clean package

  build-gateway:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.x"
          cache: true
          cache-dependency-path: app/backend/gateway/go-plugins/mindcare-auth/go.sum

      - name: Build Go Plugin
        working-directory: ./app/backend/gateway/go-plugins/mindcare-auth
        run: go build -v ./...

      - name: Test Go Plugin
        working-directory: ./app/backend/gateway/go-plugins/mindcare-auth
        run: go test -v ./...

      - name: Build Gateway Docker Image
        run: docker build -f ./app/backend/gateway/Dockerfile -t api-gateway:ci ./app/backend/gateway

  build-assessment-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: app/backend/assessment-service/requirements.txt

      - name: Install dependencies
        working-directory: ./app/backend/assessment-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile python files
        working-directory: ./app/backend/assessment-service
        run: python -m compileall app